In [1]:
import os
os.chdir("../../")#与easymlops同级目录

### 拆分数据

In [2]:
import pandas as pd
data=pd.read_csv("./data/demo.csv")
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
x_train=data[:500]
x_test=data[500:]
y_train=x_train["Survived"]
y_test=x_test["Survived"]
del x_train["Survived"]
del x_test["Survived"]

### pipe构建

In [4]:
from easymlops import NLPPipeline
from easymlops.table.preprocessing import *
from easymlops.table.ensemble import *
from easymlops.nlp.preprocessing import *
from easymlops.nlp.representation import *
from easymlops.table.perfopt import *

In [7]:
nlp=NLPPipeline()
nlp.pipe(FixInput())\
   .pipe(FillNa(cols=["Name","Age"]))\
   .pipe(SelectCols(cols=["Name","Age"]))\
   .pipe(Lower(cols=["Name"]))\
   .pipe(ReplacePunctuation(cols=["Name"],symbols=""))\
   .pipe(SelectCols(cols=["Age","Name"]))\
   .pipe(Parallel([LsiTopicModel(cols=["Name"],num_topics=4),Word2VecModel(embedding_size=4,cols=["Name"])]))\
   .pipe(DropCols(cols=["Name"]))

x_test_new=nlp.fit(x_train).transform(x_test)
x_test_new.head(5)

,lsi_Name_0,lsi_Name_1,lsi_Name_2,lsi_Name_3,w2v_Name_0,w2v_Name_1,w2v_Name_2,w2v_Name_3
500,0.985461,-0.006946,-0.049791,-0.094111,-0.016030,0.003412,0.131879,0.227311
501,0.001775,1.027365,-0.072621,-0.017235,-0.168437,-0.080284,0.188844,0.057639
502,0.001779,1.035633,-0.074136,-0.017015,-0.168437,-0.080284,0.188844,0.057639
503,0.001210,0.985790,-0.123129,0.009483,-0.233626,-0.181061,0.165193,0.226518
504,0.001197,0.968348,-0.120913,0.007778,-0.233626,-0.181061,0.165193,0.226518

### 性能、一致性测试

In [8]:
nlp.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.18ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.SelectCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.Lower'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.ReplacePunctuation'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.SelectCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[1.79ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.DropCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[2.59ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [null value] complete,speed:[2.42ms]/it,cpu:[0%],memory:[0K]
column:[Name] check [null value] complete,speed:[2.85ms]/it,cpu:[0%],memory:[0K]
column:[Sex] check [null value] complete,speed:[2.9ms]/it,cpu:[0%],memory:[0K]
column:[Age] check [null value] complete,speed:[2.34ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [null value] complete,speed:[2.79ms]/it,cpu:[16%],memory:[0K]
column:[Parch] check [null value] complete,speed:[2.61ms]/it,cpu:[0%],memory:[0K]
column:[Ticket] check [null value] complete,speed:[2.78ms]/it,cpu:[0%],memory:[0K]
column:[Fare] check [null value] complete,speed:[2.48ms]/it,cpu:[0%],memory:[0K]
column:[Cabin] check [null value] complete,speed:[2.44ms]/it,cpu:[0%],memory:[0K]
column:[Embarked] check [null value] complete,speed:[2.14ms]/it,cpu:[0%],memory:[0K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[2.27ms]/it,cpu:[44%],memory:[7478368K]
column:[Pclass] check [extreme value] complete,speed:[2.36ms]/it,cpu:[33%],memory:[7478392K]
column:[Name] check [extreme value] complete,speed:[2.85ms]/it,cpu:[0%],memory:[0K]
column:[Sex] check [extreme value] complete,speed:[1.97ms]/it,cpu:[33%],memory:[7478384K]
column:[Age] check [extreme value] complete,speed:[2.44ms]/it,cpu:[50%],memory:[7478488K]
column:[SibSp] check [extreme value] complete,speed:[3.13ms]/it,cpu:[100%],memory:[7478444K]
column:[Parch] check [extreme value] complete,speed:[2.88ms]/it,cpu:[66%],memory:[7492256K]
column:[Ticket] check [extreme value] complete,speed:[2.71ms]/it,cpu:[27%],memory:[7492392K]
column:[Fare] check [extreme value] complete,speed:[2.9ms]/it,cpu:[100%],memory:[7501860K]
column:[Cabin] check [extreme value] complete,speed:[3.19ms]/it,cpu:[57%],memory:[7509772K]
column:[Embarked] check [extreme value] complete,speed:[3.13ms]/it,cpu:[22%],memory:[7497176K]
column:[__all__] check [extreme value] complete,speed:[3.02ms]/it,cpu:[42%],memory:[7495792K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[3.35ms]/it,cpu:[44%],memory:[7495444K]
column:[Pclass] check [inverse type] complete,speed:[2.23ms]/it,cpu:[42%],memory:[7495128K]
column:[Name] check [inverse type] complete,speed:[2.65ms]/it,cpu:[16%],memory:[7495028K]
column:[Sex] check [inverse type] complete,speed:[2.68ms]/it,cpu:[27%],memory:[7495000K]
column:[Age] check [inverse type] complete,speed:[2.07ms]/it,cpu:[37%],memory:[7494964K]
column:[SibSp] check [inverse type] complete,speed:[2.67ms]/it,cpu:[31%],memory:[7494952K]
column:[Parch] check [inverse type] complete,speed:[2.23ms]/it,cpu:[16%],memory:[7494916K]
column:[Ticket] check [inverse type] complete,speed:[2.32ms]/it,cpu:[16%],memory:[7494936K]
column:[Fare] check [inverse type] complete,speed:[2.92ms]/it,cpu:[16%],memory:[7494932K]
column:[Cabin] check [inverse type] complete,speed:[3.24ms]/it,cpu:[53%],memory:[7542736K]
column:[Embarked] check [inverse type] complete,speed:[2.33ms]/it,cpu:[66%],memory:[7561544K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################
column:[PassengerId] check [int trans float] complete,speed:[3.13ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [int trans float] complete,speed:[3.24ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [int trans float] complete,speed:[3.59ms]/it,cpu:[0%],memory:[0K]
column:[Parch] check [int trans float] complete,speed:[3.13ms]/it,cpu:[0%],memory:[0K]

### 持久化测试

In [9]:
nlp.save("ml.pkl")

In [10]:
nlp=NLPPipeline()
nlp.pipe(FixInput())\
   .pipe(FillNa(cols=["Name","Age"]))\
   .pipe(SelectCols(cols=["Name","Age"]))\
   .pipe(Lower(cols=["Name"]))\
   .pipe(ReplacePunctuation(cols=["Name"],symbols=""))\
   .pipe(SelectCols(cols=["Age","Name"]))\
   .pipe(Parallel([LsiTopicModel(cols=["Name"],num_topics=4),Word2VecModel(embedding_size=4,cols=["Name"])]))\
   .pipe(DropCols(cols=["Name"]))

nlp.load("ml.pkl")

In [11]:
nlp.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.SelectCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.Lower'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.ReplacePunctuation'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.SelectCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[3.13ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.DropCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[3.09ms]/it,cpu:[38%],memory:[0K]
column:[Pclass] check [null value] complete,speed:[2.46ms]/it,cpu:[0%],memory:[0K]
column:[Name] check [null value] complete,speed:[3.18ms]/it,cpu:[0%],memory:[0K]
column:[Sex] check [null value] complete,speed:[3.12ms]/it,cpu:[16%],memory:[0K]
column:[Age] check [null value] complete,speed:[3.32ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [null value] complete,speed:[3.24ms]/it,cpu:[0%],memory:[0K]
column:[Parch] check [null value] complete,speed:[3.02ms]/it,cpu:[0%],memory:[0K]
column:[Ticket] check [null value] complete,speed:[3.12ms]/it,cpu:[0%],memory:[0K]
column:[Fare] check [null value] complete,speed:[2.92ms]/it,cpu:[33%],memory:[0K]
column:[Cabin] check [null value] complete,speed:[2.16ms]/it,cpu:[0%],memory:[0K]
column:[Embarked] check [null value] complete,speed:[3.22ms]/it,cpu:[0%],memory:[0K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[3.12ms]/it,cpu:[16%],memory:[7510204K]
column:[Pclass] check [extreme value] complete,speed:[2.5ms]/it,cpu:[25%],memory:[7506840K]
column:[Name] check [extreme value] complete,speed:[2.75ms]/it,cpu:[27%],memory:[7506840K]
column:[Sex] check [extreme value] complete,speed:[1.92ms]/it,cpu:[16%],memory:[7509604K]
column:[Age] check [extreme value] complete,speed:[3.12ms]/it,cpu:[63%],memory:[7505552K]
column:[SibSp] check [extreme value] complete,speed:[2.85ms]/it,cpu:[28%],memory:[7505320K]
column:[Parch] check [extreme value] complete,speed:[2.76ms]/it,cpu:[42%],memory:[7505972K]
column:[Ticket] check [extreme value] complete,speed:[2.97ms]/it,cpu:[33%],memory:[7501904K]
column:[Fare] check [extreme value] complete,speed:[3.17ms]/it,cpu:[33%],memory:[7501908K]
column:[Cabin] check [extreme value] complete,speed:[2.35ms]/it,cpu:[27%],memory:[7498492K]
column:[Embarked] check [extreme value] complete,speed:[2.81ms]/it,cpu:[0%],memory:[0K]
column:[__all__] check [extreme value] complete,speed:[3.56ms]/it,cpu:[28%],memory:[7498492K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[3.8ms]/it,cpu:[30%],memory:[7495752K]
column:[Pclass] check [inverse type] complete,speed:[3.81ms]/it,cpu:[100%],memory:[7494116K]
column:[Name] check [inverse type] complete,speed:[2.51ms]/it,cpu:[50%],memory:[7491924K]
column:[Sex] check [inverse type] complete,speed:[2.26ms]/it,cpu:[16%],memory:[7491864K]
column:[Age] check [inverse type] complete,speed:[2.03ms]/it,cpu:[16%],memory:[7491884K]
column:[SibSp] check [inverse type] complete,speed:[2.46ms]/it,cpu:[68%],memory:[7494792K]
column:[Parch] check [inverse type] complete,speed:[3.9ms]/it,cpu:[100%],memory:[7490560K]
column:[Ticket] check [inverse type] complete,speed:[3.11ms]/it,cpu:[75%],memory:[7493160K]
column:[Fare] check [inverse type] complete,speed:[2.9ms]/it,cpu:[45%],memory:[7490488K]
column:[Cabin] check [inverse type] complete,speed:[2.8ms]/it,cpu:[0%],memory:[0K]
column:[Embarked] check [inverse type] complete,speed:[2.44ms]/it,cpu:[50%],memory:[7487416K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################
column:[PassengerId] check [int trans float] complete,speed:[3.58ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [int trans float] complete,speed:[3.12ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [int trans float] complete,speed:[3.13ms]/it,cpu:[22%],memory:[0K]
column:[Parch] check [int trans float] complete,speed:[3.15ms]/it,cpu:[25%],memory:[0K]

In [12]:
nlp.transform(x_test[:5])

,lsi_Name_0,lsi_Name_1,lsi_Name_2,lsi_Name_3,w2v_Name_0,w2v_Name_1,w2v_Name_2,w2v_Name_3
500,0.985461,-0.006946,-0.049791,-0.094111,-0.016030,0.003412,0.131879,0.227311
501,0.001775,1.027365,-0.072621,-0.017235,-0.168437,-0.080284,0.188844,0.057639
502,0.001779,1.035633,-0.074136,-0.017015,-0.168437,-0.080284,0.188844,0.057639
503,0.001210,0.985790,-0.123129,0.009483,-0.233626,-0.181061,0.165193,0.226518
504,0.001197,0.968348,-0.120913,0.007778,-0.233626,-0.181061,0.165193,0.226518

In [13]:
x_test_new.head(5)

,lsi_Name_0,lsi_Name_1,lsi_Name_2,lsi_Name_3,w2v_Name_0,w2v_Name_1,w2v_Name_2,w2v_Name_3
500,0.985461,-0.006946,-0.049791,-0.094111,-0.016030,0.003412,0.131879,0.227311
501,0.001775,1.027365,-0.072621,-0.017235,-0.168437,-0.080284,0.188844,0.057639
502,0.001779,1.035633,-0.074136,-0.017015,-0.168437,-0.080284,0.188844,0.057639
503,0.001210,0.985790,-0.123129,0.009483,-0.233626,-0.181061,0.165193,0.226518
504,0.001197,0.968348,-0.120913,0.007778,-0.233626,-0.181061,0.165193,0.226518